public class IndividualSuite1 {
        public String color{get;set;}
        public String textcolor{get;set;}
        public String Name{get;set;}
        public String SuiteNumber{get;set;}
		public Decimal SuiteNumberSort{get;set;}        
        public Decimal SuiteRSF{get;set;}
        public String SuiteLEXP{get;set;}
        public String Address{get;set;}
        public String Vacant{get;set;}
        
        public String Link{get;set;}
        public String SuiteLink{get;set;}
}